import { Store, Profile, Category, Supplier, Customer, Product, CashRegister, Sale, StockMovement, AccountReceivable, Expense } from './db/types';

export const INITIAL_STORE: Store = {
  id: 'store-1',
  name: 'VasiStore Gestão de Utilidades',
  trade_name: 'VasiStore',
  cnpj_cpf: '',
  phone: '',
  whatsapp: '',
  email: 'contato@vasistore.com.br',
  address: '',
  number: '',
  neighborhood: '',
  city: '',
  state: '',
  zip_code: '',
  logo_url: '/logo.png',
  receipt_message: 'Obrigado pela preferência! Volte sempre.',
  pix_key: '08395029667',
  pix_beneficiary_name: 'VasiStore Gestão de Utilidades',
  pix_city: 'Brasília',
  currency: 'BRL',
  timezone: 'America/Sao_Paulo',
  active: true,
  created_at: new Date().toISOString(),
};

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-medalha25',
    store_id: 'store-1',
    email: 'medalha25@gmail.com',
    full_name: 'Wesley Medalha (Administrador Geral)',
    role: 'admin',
    phone: '',
    password: '15252833',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-weslley',
    store_id: 'store-1',
    email: 'weslley@donalar.com.br',
    full_name: 'Weslley (ADM Suporte)',
    role: 'admin',
    phone: '',
    password: '15252833',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-admin',
    store_id: 'store-1',
    email: 'aguilarsuriel6@gmail.com',
    full_name: 'Suriel Aguilar (ADM)',
    role: 'admin',
    phone: '',
    password: '123',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-manager',
    store_id: 'store-1',
    email: 'joel@donalar.com.br',
    full_name: 'Joel (Gerente)',
    role: 'gerente',
    phone: '',
    password: '123',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-seller',
    store_id: 'store-1',
    email: 'elizangela@donalar.com.br',
    full_name: 'Elizangela (Vendedora)',
    role: 'vendedor',
    phone: '',
    password: '123',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-cashier',
    store_id: 'store-1',
    email: 'caixa@donalar.com.br',
    full_name: 'Caixa (Operador de Caixa)',
    role: 'caixa',
    phone: '',
    password: '123',
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    store_id: 'store-1',
    name: 'Potes e Vasilhas',
    slug: 'potes-e-vasilhas',
    description: 'Potes herméticos, potes de vidro, conjuntos de vasilhas plásticas',
    icon: 'Package',
    color: '#16a34a',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    store_id: 'store-1',
    name: 'Organizadores e Caixas',
    slug: 'organizadores-e-caixas',
    description: 'Caixas organizadoras com travas, organizadores de gaveta e acrílicos',
    icon: 'Layers',
    color: '#0284c7',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    store_id: 'store-1',
    name: 'Panelas e Frigideiras',
    slug: 'panelas-e-frigideiras',
    description: 'Conjuntos de panelas, caçarolas, frigideiras e panelas de pressão',
    icon: 'Flame',
    color: '#ea580c',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    store_id: 'store-1',
    name: 'Copos, Taças e Jarras',
    slug: 'copos-tacas-e-jarras',
    description: 'Jogos de copos de vidro, taças, jarras graduadas e acrílicas',
    icon: 'Wine',
    color: '#8b5cf6',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    store_id: 'store-1',
    name: 'Talheres e Facas',
    slug: 'talheres-e-facas',
    description: 'Faqueiros inox, facas de corte, conchas e espátulas de silicone',
    icon: 'UtensilsCrossed',
    color: '#64748b',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    store_id: 'store-1',
    name: 'Pratos e Louças',
    slug: 'pratos-e-loucas',
    description: 'Pratos rasos, fundos, sobremesa, travessas e refratários',
    icon: 'Disc',
    color: '#0d9488',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-7',
    store_id: 'store-1',
    name: 'Garrafas e Térmicas',
    slug: 'garrafas-e-termicas',
    description: 'Garrafas de café térmicas, squeezes inox e garrafas térmicas',
    icon: 'Coffee',
    color: '#b45309',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-8',
    store_id: 'store-1',
    name: 'Utilidades e Alumínio',
    slug: 'utilidades-e-aluminio',
    description: 'Caldeirões industriais, jogos de latas, bacias e utilidades de alumínio',
    icon: 'Utensils',
    color: '#059669',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-9',
    store_id: 'store-1',
    name: 'Limpeza e Lavanderia',
    slug: 'limpeza-e-lavanderia',
    description: 'Mops giratórios, baldes graduados, bacias e pregadores',
    icon: 'Sparkles',
    color: '#3b82f6',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-10',
    store_id: 'store-1',
    name: 'Churrasco & Lazer',
    slug: 'churrasco-e-lazer',
    description: 'Churrasqueiras portáteis, quadradas, meia redonda e grelhas',
    icon: 'Flame',
    color: '#dc2626',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-11',
    store_id: 'store-1',
    name: 'Cama, Mesa & Decoração',
    slug: 'cama-mesa-e-decoracao',
    description: 'Travesseiros confortáveis, almofadas de sofá e itens para o lar',
    icon: 'Package',
    color: '#d97706',
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-12',
    store_id: 'store-1',
    name: 'Calçados & Vestuário',
    slug: 'calcados-e-vestuario',
    description: 'Botinas de couro reforçadas, calçados e botas de trabalho',
    icon: 'Package',
    color: '#78350f',
    active: true,
    created_at: new Date().toISOString(),
  },
];

const RAW_PRODUCTS = [
  { id: 'prod-1', cat: 'cat-3', sku: 'PAN-1001', bar: '7892026001015', name: 'Jogo de panelas coloridas tampo de vidro', desc: 'Conjunto completo de panelas coloridas com tampa de vidro temperado e saída de vapor.', brand: 'Nacional', unit: 'kit' as const, cost: 160.00, sale: 285.00, stock: 10, min: 3, max: 30 },
  { id: 'prod-2', cat: 'cat-3', sku: 'PAN-1002', bar: '7892026001022', name: 'Jogo de panelas coloridas tampo comum', desc: 'Conjunto de panelas coloridas resistentes com tampa de alumínio tradicional.', brand: 'Nacional', unit: 'kit' as const, cost: 105.00, sale: 185.00, stock: 12, min: 3, max: 30 },
  { id: 'prod-3', cat: 'cat-3', sku: 'PAN-1003', bar: '7892026001039', name: 'Panela alumínio batido 6,5 L', desc: 'Panela reforçada em alumínio fundido/batido grosso com capacidade de 6,5 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 105.00, sale: 185.00, stock: 15, min: 4, max: 40 },
  { id: 'prod-4', cat: 'cat-3', sku: 'PAN-1004', bar: '7892026001046', name: 'Panela alumínio claro 6,5 L', desc: 'Panela em alumínio polido claro de alta qualidade com 6,5 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 98.00, sale: 175.00, stock: 15, min: 4, max: 40 },
  { id: 'prod-5', cat: 'cat-3', sku: 'PAN-1005', bar: '7892026001053', name: 'Panela alumínio Preta 7,5 L', desc: 'Panela grande com acabamento craqueado preto resistente e capacidade de 7,5 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 105.00, sale: 185.00, stock: 12, min: 3, max: 30 },
  { id: 'prod-6', cat: 'cat-3', sku: 'PAN-1006', bar: '7892026001060', name: 'Panela alumínio escura 5,5 L', desc: 'Panela com acabamento escuro especial de 5,5 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 92.00, sale: 165.00, stock: 14, min: 3, max: 35 },
  { id: 'prod-7', cat: 'cat-3', sku: 'PAN-1007', bar: '7892026001077', name: 'Jogo de panela preta tampa comum alumínio reforçado', desc: 'Jogo completo de panelas pretas reforçadas com tampa de alumínio comum.', brand: 'Alumínio Forte', unit: 'kit' as const, cost: 110.00, sale: 195.00, stock: 10, min: 3, max: 25 },
  { id: 'prod-8', cat: 'cat-3', sku: 'PAN-1008', bar: '7892026001084', name: 'Jogo de panela alumínio claro fundo', desc: 'Jogo de panelas de alumínio claro com fundo espesso para melhor distribuição de calor.', brand: 'Alumínio Forte', unit: 'kit' as const, cost: 108.00, sale: 189.00, stock: 10, min: 3, max: 25 },
  { id: 'prod-9', cat: 'cat-3', sku: 'PAN-1009', bar: '7892026001091', name: 'Panela de pressão 10 L', desc: 'Panela de pressão de grande porte 10 litros com válvula de segurança aprovada pelo Inmetro.', brand: 'Pressão Forte', unit: 'unidade' as const, cost: 165.00, sale: 280.00, stock: 8, min: 2, max: 20 },
  { id: 'prod-10', cat: 'cat-3', sku: 'PAN-1010', bar: '7892026001107', name: 'Panela de pressão 7 L', desc: 'Panela de pressão de 7 litros com fechamento seguro e alto rendimento térmico.', brand: 'Pressão Forte', unit: 'unidade' as const, cost: 148.00, sale: 259.00, stock: 10, min: 3, max: 25 },
  { id: 'prod-11', cat: 'cat-3', sku: 'PAN-1011', bar: '7892026001114', name: 'Panela caçarola 8,5 L', desc: 'Caçarola grande de 8,5 litros com asas anatômicas e tampa reforçada.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 74.00, sale: 129.00, stock: 15, min: 3, max: 35 },
  { id: 'prod-12', cat: 'cat-3', sku: 'PAN-1012', bar: '7892026001121', name: 'Panela caçarola 8 L', desc: 'Caçarola de alumínio reforçado com 8 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 70.00, sale: 124.00, stock: 15, min: 3, max: 35 },
  { id: 'prod-13', cat: 'cat-3', sku: 'PAN-1013', bar: '7892026001138', name: 'Panela caçarola 6 L', desc: 'Caçarola de alumínio com 6 litros, ideal para o dia a dia.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 68.00, sale: 119.90, stock: 18, min: 4, max: 40 },
  { id: 'prod-14', cat: 'cat-3', sku: 'PAN-1014', bar: '7892026001145', name: 'Panela caçarola fundida preta 5,250 L', desc: 'Caçarola em ferro/alumínio fundido preto de 5,25 litros com retenção prolongada de calor.', brand: 'Fundição Nobre', unit: 'unidade' as const, cost: 94.00, sale: 165.00, stock: 12, min: 3, max: 30 },
  { id: 'prod-15', cat: 'cat-3', sku: 'PAN-1015', bar: '7892026001152', name: 'Panela caçarola fundida preta 5,5 L', desc: 'Caçarola fundida preta espessa com 5,5 litros de capacidade.', brand: 'Fundição Nobre', unit: 'unidade' as const, cost: 105.00, sale: 185.00, stock: 12, min: 3, max: 30 },
  { id: 'prod-16', cat: 'cat-3', sku: 'PAN-1016', bar: '7892026001169', name: 'Tacho fundido 3,5 L', desc: 'Tacho fundido para doces, frituras e preparos artesanais com 3,5 litros.', brand: 'Fundição Nobre', unit: 'unidade' as const, cost: 80.00, sale: 143.00, stock: 14, min: 3, max: 30 },
  { id: 'prod-17', cat: 'cat-3', sku: 'PAN-1017', bar: '7892026001176', name: 'Frigideira alumínio batido', desc: 'Frigideira grossa em alumínio batido com cabo de baquelite reforçado.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 58.00, sale: 106.80, stock: 20, min: 5, max: 50 },
  { id: 'prod-18', cat: 'cat-3', sku: 'PAN-1018', bar: '7892026001183', name: 'Panela caçarola 22', desc: 'Panela caçarola número 22 cm em alumínio.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 36.00, sale: 65.90, stock: 25, min: 5, max: 60 },
  { id: 'prod-19', cat: 'cat-3', sku: 'PAN-1019', bar: '7892026001190', name: 'Panela caçarola 20', desc: 'Panela caçarola número 20 cm em alumínio.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 30.00, sale: 55.00, stock: 25, min: 5, max: 60 },
  { id: 'prod-20', cat: 'cat-3', sku: 'PAN-1020', bar: '7892026001206', name: 'Jogo de panela caçarola redonda', desc: 'Conjunto de caçarolas redondas em alumínio reforçado.', brand: 'Alumínio Forte', unit: 'kit' as const, cost: 95.00, sale: 170.00, stock: 12, min: 3, max: 30 },
  { id: 'prod-21', cat: 'cat-8', sku: 'CAL-2001', bar: '7892026002012', name: 'Caldeirão 25 L', desc: 'Caldeirão industrial de alumínio reforçado com asas reforçadas e capacidade de 25 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 105.00, sale: 185.00, stock: 8, min: 2, max: 20 },
  { id: 'prod-22', cat: 'cat-8', sku: 'CAL-2002', bar: '7892026002029', name: 'Caldeirão 20 L', desc: 'Caldeirão de alumínio grosso com capacidade de 20 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 96.00, sale: 169.90, stock: 10, min: 2, max: 25 },
  { id: 'prod-23', cat: 'cat-8', sku: 'CAL-2003', bar: '7892026002036', name: 'Caldeirão 16 L', desc: 'Caldeirão de alumínio com capacidade de 16 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 85.00, sale: 149.90, stock: 12, min: 3, max: 30 },
  { id: 'prod-24', cat: 'cat-8', sku: 'CAL-2004', bar: '7892026002043', name: 'Caldeirão 14 L', desc: 'Caldeirão de alumínio resistente de 14 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 78.00, sale: 139.00, stock: 12, min: 3, max: 30 },
  { id: 'prod-25', cat: 'cat-8', sku: 'CAL-2005', bar: '7892026002050', name: 'Caldeirão 12 L', desc: 'Caldeirão de alumínio de 12 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 72.00, sale: 129.90, stock: 15, min: 3, max: 35 },
  { id: 'prod-26', cat: 'cat-8', sku: 'CAL-2006', bar: '7892026002067', name: 'Caldeirão 10 L', desc: 'Caldeirão de alumínio de 10 litros.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 66.00, sale: 119.90, stock: 15, min: 3, max: 35 },
  { id: 'prod-27', cat: 'cat-8', sku: 'ALU-3001', bar: '7892026003019', name: 'Jogo de lata de alumínio', desc: 'Conjunto de latas / mantimentos em alumínio com tampas herméticas.', brand: 'Alumínio Forte', unit: 'kit' as const, cost: 88.00, sale: 159.90, stock: 10, min: 3, max: 25 },
  { id: 'prod-28', cat: 'cat-8', sku: 'ALU-3002', bar: '7892026003026', name: 'Bacia de alumínio grande', desc: 'Bacia reforçada de alumínio grande para preparos culinários e lavanderia.', brand: 'Alumínio Forte', unit: 'unidade' as const, cost: 42.00, sale: 79.90, stock: 16, min: 4, max: 40 },
  { id: 'prod-29', cat: 'cat-8', sku: 'ALU-3003', bar: '7892026003033', name: 'Jogo de 5 latas de alumínio', desc: 'Jogo completo com 5 latas de mantimentos (Arroz, Feijão, Açúcar, Café e Farinha).', brand: 'Alumínio Forte', unit: 'kit' as const, cost: 102.00, sale: 185.00, stock: 10, min: 3, max: 25 },
  { id: 'prod-30', cat: 'cat-12', sku: 'CAL-4001', bar: '7892026004016', name: 'Botina amarela', desc: 'Botina de segurança e trabalho em couro nobuck amarelo com elástico lateral e solado antiderrapante.', brand: 'Couro Forte', unit: 'par' as const, cost: 52.00, sale: 93.90, stock: 20, min: 5, max: 50 },
  { id: 'prod-31', cat: 'cat-12', sku: 'CAL-4002', bar: '7892026004023', name: 'Botina marrom', desc: 'Botina em couro legítimo marrom com acabamento reforçado e palmilha confortável.', brand: 'Couro Forte', unit: 'par' as const, cost: 68.00, sale: 125.00, stock: 18, min: 4, max: 45 },
  { id: 'prod-32', cat: 'cat-11', sku: 'DEC-5001', bar: '7892026005013', name: 'Travesseiros', desc: 'Travesseiro macio com fibra siliconada antialérgica e tecido toque suave.', brand: 'Confort Lar', unit: 'unidade' as const, cost: 18.00, sale: 35.00, stock: 30, min: 8, max: 80 },
  { id: 'prod-33', cat: 'cat-11', sku: 'DEC-5002', bar: '7892026005020', name: 'Almofada de sofá', desc: 'Almofada decorativa para sofá com enchimento confortável e capa removível.', brand: 'Confort Lar', unit: 'unidade' as const, cost: 17.50, sale: 34.90, stock: 30, min: 8, max: 80 },
  { id: 'prod-34', cat: 'cat-10', sku: 'CHU-6001', bar: '7892026006010', name: 'Churrasqueira meia redonda', desc: 'Churrasqueira a carvão modelo meia redonda em chapa de aço com grelha e pés de apoio.', brand: 'Churrasco Grill', unit: 'unidade' as const, cost: 220.00, sale: 399.90, stock: 6, min: 2, max: 15 },
  { id: 'prod-35', cat: 'cat-10', sku: 'CHU-6002', bar: '7892026006027', name: 'Churrasqueira quadrada desmontável', desc: 'Churrasqueira portátil quadrada totalmente desmontável com grelha em inox.', brand: 'Churrasco Grill', unit: 'unidade' as const, cost: 210.00, sale: 380.00, stock: 6, min: 2, max: 15 },
  { id: 'prod-36', cat: 'cat-10', sku: 'CHU-6003', bar: '7892026006034', name: 'Churrasqueira quadrada', desc: 'Churrasqueira quadrada reforçada com grelha, suporte lateral e acabamento esmaltado.', brand: 'Churrasco Grill', unit: 'unidade' as const, cost: 250.00, sale: 450.00, stock: 5, min: 2, max: 15 },
];

export const INITIAL_PRODUCTS: Product[] = RAW_PRODUCTS.map((p) => ({
  id: p.id,
  store_id: 'store-1',
  category_id: p.cat,
  sku: p.sku,
  barcode: p.bar,
  name: p.name,
  description: p.desc,
  brand: p.brand,
  unit: p.unit,
  cost_price: p.cost,
  sale_price: p.sale,
  profit_margin: Number((((p.sale - p.cost) / p.cost) * 100).toFixed(2)),
  current_stock: p.stock,
  min_stock: p.min,
  max_stock: p.max,
  active: true,
  created_at: new Date().toISOString(),
}));

// Dados operacionais limpos prontos para novas vendas reais
export const INITIAL_SUPPLIERS: Supplier[] = [];
export const INITIAL_CUSTOMERS: Customer[] = [];
export const INITIAL_CASH_REGISTERS: CashRegister[] = [];
export const INITIAL_SALES: Sale[] = [];
export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [];
export const INITIAL_ACCOUNTS_RECEIVABLE: AccountReceivable[] = [];
export const INITIAL_EXPENSES: Expense[] = [];
